/*
 * CAfficheurHtml.java
 *
 * Created on 17 novembre 2006, 16:09
 */

package livret;

import java.io.IOException;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author  bruno
 */
public class CAfficheurHtml extends javax.swing.JFrame {

    private int m_height;
    private int m_width;
    
    /** Creates new form CAfficheurHtml */
    public CAfficheurHtml(String ressourceFileName, int width, int heigth) {
        m_width = width;
        m_height = heigth;
        initComponents();
        try {
            editorPane.setPage(this.getClass().getResource(ressourceFileName));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Impossible d'ouvrir le fichier ...",
                    "Erreur", JOptionPane.ERROR_MESSAGE);
            System.out.println("Impossible d'ouvrir la ressource : " + ressourceFileName);
        }
        this.setSize(m_width, m_height);
    }

    public CAfficheurHtml(String htmlFile) {
        this(htmlFile, 450, 400);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();
        bouttonFermer = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(450, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(600, 800));
        editorPane.setEditable(false);
        editorPane.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(editorPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        bouttonFermer.setFont(new java.awt.Font("Dialog", 0, 12));
        bouttonFermer.setText("fermer");
        bouttonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonFermerActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        add(bouttonFermer, gridBagConstraints);

    }// </editor-fold>//GEN-END:initComponents
    
    private void bouttonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonFermerActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bouttonFermerActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouttonFermer;
    private javax.swing.JEditorPane editorPane;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
